# Generated by Django 5.1.1 on 2024-09-20 20:02

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coreapp.base')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('task', tinymce.models.HTMLField(blank=True, null=True)),
                ('timelimit', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('N', 'Not Started'), ('Ip', 'In Progress'), ('Uc', 'Uncomplete'), ('C', 'Completed')], max_length=256)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('time_limit', models.DurationField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            bases=('coreapp.base',),
        ),
    ]
