# Generated by Django 5.1.1 on 2024-09-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
