# Generated by Django 5.1.1 on 2024-09-20 20:02

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreapp', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTree',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coreapp.base')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('associated_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.playerprofile')),
            ],
            bases=('coreapp.base',),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coreapp.base')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('main_goal', tinymce.models.HTMLField(blank=True, null=True)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('skill_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skilltree')),
            ],
            bases=('coreapp.base',),
        ),
    ]
