# Generated by Django 5.1.1 on 2024-09-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skilltree',
            name='Xp_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skilltree',
            name='level',
            field=models.IntegerField(default=0),
        ),
    ]
