# Generated by Django 5.1.1 on 2024-09-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_skilltree_xp_points_skilltree_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skilltree',
            old_name='Xp_points',
            new_name='skill_points',
        ),
        migrations.AddField(
            model_name='skilltree',
            name='xp_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
