# Generated by Django 5.1.1 on 2024-09-21 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_rename_xp_points_skilltree_skill_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltree',
            name='xp_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
