# Generated by Django 5.1.1 on 2024-09-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_alter_skilltree_xp_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skilltree',
            name='skill_points',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
