# Generated by Django 5.1.1 on 2024-09-20 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('base_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='coreapp.base')),
                ('username', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.CharField(blank=True, max_length=500, null=True)),
                ('life_goals', models.TextField(blank=True, null=True)),
                ('level', models.IntegerField(default=0)),
                ('Xp_points', models.IntegerField(blank=True, null=True)),
                ('player_streak', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            bases=('coreapp.base',),
        ),
    ]
