# Generated by Django 5.1.1 on 2024-09-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerprofile',
            name='Xp_points',
        ),
        migrations.RemoveField(
            model_name='playerprofile',
            name='level',
        ),
    ]
